/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TecnologiaImport } from './routes/tecnologia'
import { Route as OpinionesImport } from './routes/opiniones'
import { Route as EstadisticasImport } from './routes/estadisticas'
import { Route as IndexImport } from './routes/index'
import { Route as PostsIdImport } from './routes/posts/$id'

// Create/Update Routes

const TecnologiaRoute = TecnologiaImport.update({
  id: '/tecnologia',
  path: '/tecnologia',
  getParentRoute: () => rootRoute,
} as any)

const OpinionesRoute = OpinionesImport.update({
  id: '/opiniones',
  path: '/opiniones',
  getParentRoute: () => rootRoute,
} as any)

const EstadisticasRoute = EstadisticasImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PostsIdRoute = PostsIdImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/estadisticas': {
      id: '/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof EstadisticasImport
      parentRoute: typeof rootRoute
    }
    '/opiniones': {
      id: '/opiniones'
      path: '/opiniones'
      fullPath: '/opiniones'
      preLoaderRoute: typeof OpinionesImport
      parentRoute: typeof rootRoute
    }
    '/tecnologia': {
      id: '/tecnologia'
      path: '/tecnologia'
      fullPath: '/tecnologia'
      preLoaderRoute: typeof TecnologiaImport
      parentRoute: typeof rootRoute
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estadisticas': typeof EstadisticasRoute
  '/opiniones': typeof OpinionesRoute
  '/tecnologia': typeof TecnologiaRoute
  '/posts/$id': typeof PostsIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estadisticas': typeof EstadisticasRoute
  '/opiniones': typeof OpinionesRoute
  '/tecnologia': typeof TecnologiaRoute
  '/posts/$id': typeof PostsIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/estadisticas': typeof EstadisticasRoute
  '/opiniones': typeof OpinionesRoute
  '/tecnologia': typeof TecnologiaRoute
  '/posts/$id': typeof PostsIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/estadisticas' | '/opiniones' | '/tecnologia' | '/posts/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/estadisticas' | '/opiniones' | '/tecnologia' | '/posts/$id'
  id:
    | '__root__'
    | '/'
    | '/estadisticas'
    | '/opiniones'
    | '/tecnologia'
    | '/posts/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstadisticasRoute: typeof EstadisticasRoute
  OpinionesRoute: typeof OpinionesRoute
  TecnologiaRoute: typeof TecnologiaRoute
  PostsIdRoute: typeof PostsIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstadisticasRoute: EstadisticasRoute,
  OpinionesRoute: OpinionesRoute,
  TecnologiaRoute: TecnologiaRoute,
  PostsIdRoute: PostsIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/estadisticas",
        "/opiniones",
        "/tecnologia",
        "/posts/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/estadisticas": {
      "filePath": "estadisticas.tsx"
    },
    "/opiniones": {
      "filePath": "opiniones.tsx"
    },
    "/tecnologia": {
      "filePath": "tecnologia.tsx"
    },
    "/posts/$id": {
      "filePath": "posts/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
